# Generated by Django 5.0.7 on 2024-09-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0004_menulink_favicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menulink',
            name='favicon',
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assets/favicon/%Y/%m/'),
        ),
    ]
